version: '3.8'

services:
  backend:
    build:
      context: ./backend  # path to your backend Dockerfile folder
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend  # path to your frontend Dockerfile folder
    container_name: frontend
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
